// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA250K0oVBciCpNq6s8KSb72biKgKSnVmw',
    appId: '1:186440052923:android:9bea30ff603906c398399e',
    messagingSenderId: '186440052923',
    projectId: 'nepisireyim',
    databaseURL: 'https://nepisireyim.firebaseio.com',
    storageBucket: 'nepisireyim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuxzTCceg31xEuFnQatjXU79xN01e0fDo',
    appId: '1:186440052923:ios:2d01c94d23933ac098399e',
    messagingSenderId: '186440052923',
    projectId: 'nepisireyim',
    databaseURL: 'https://nepisireyim.firebaseio.com',
    storageBucket: 'nepisireyim.appspot.com',
    androidClientId: '186440052923-5gt3scl3l7tnkl9bv0ndkf3gglo1569i.apps.googleusercontent.com',
    iosBundleId: 'com.dumbooctopusstudios.nepisireyim',
  );
}
